version: 0.2
phases:
  install:
    commands:
      - npm i -g pnpm
      - npm install
      - npx playwright install
  build:
    commands:
      - docker run -d -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=postgres postgres
      - npm run build
  post_build:
    commands:
      - npm run test-start
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'
