# The manifest for the "prisma-starter-workloads" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: prisma-starter-workloads

# The version of the schema used in this template.
version: 1

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: GitHub
  # Additional properties that further specify the location of the artifacts.
  properties:
    branch: main
    repository: https://github.com/cornflowerblu/trpc-prisma-starter

# This section defines the order of the environments your pipeline will deploy to.
stages:
  - # The name of the environment.
    name: test
    requires_approval: false

  - # The name of the environment.
    name: prod
    requires_approval: true
    depends_on:
      - test
