name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: pre-install
        run: |
          docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres
          rm -f .env && touch .env
          echo 'DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres' > .env
          cat .env
            npm i -g pnpm prisma
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run E2E tests
        run: npm run test-start
